base_model: Qwen/Qwen2-1.5B-Instruct
trust_remote_code: true

load_in_8bit: false
load_in_4bit: true
strict: false

rl: dpo
dpo_beta: 0.1
rl_adapter_ref_model: false
datasets:
  - ds_type: json
    data_files:
      - /mnt/harddrive/datasets/text/raw_data/short_len_dpo_dataset.jsonl
    type: chatml.intel_prefilled
    split: train
dataset_prepared_path: last_run_prepared
val_set_size: 0.02
output_dir: ./checkpoints/qwen2/qwen2_1_5b_summarize_20000examples

sequence_len: 2048
sample_packing: false
pad_to_sequence_len: true

adapter: qlora
lora_model_dir:
lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: axolotl
wandb_entity: thepowerfuldeez
wandb_watch:
wandb_name: qwen2_1_5b_qlora_summarize_20000examples
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 1
num_epochs: 2
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 0.00005

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
evals_per_epoch: 4
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_limit_all_gathers: true
  fsdp_sync_module_states: true
  fsdp_offload_params: true
  fsdp_use_orig_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: Qwen2DecoderLayer
  fsdp_state_dict_type: FULL_STATE_DICT
special_tokens:
